identifier: crosses_v2
name: Crosses V2
url: https://ergokeyboards.com
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - ble
  - gpio
  - ieee802154
  - pwm
  - spi
  - usb_device
  - watchdog
