file_format: "1"
id: crosses_v2//zmk
name: Crosses V2
type: board
arch: arm
url: https://ergokeyboards.com
features:
  - keys
  - studio
  - pointer
outputs:
  - usb
  - ble
siblings:
  - crosses_v2_left
  - crosses_v2_right
