# Demote from Central to Peripheral
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Disable web config / CDC ACM on peripheral half
CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_CDC_ACM=n
CONFIG_SERIAL=n
CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_UART_LINE_CTRL=n
CONFIG_ZMK_TRACKBALL_CONFIG=n
